In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import folium
import json
import wbdata
from sklearn.cluster import KMeans 
import pylab as pl

In [2]:
path = r"C:\Users\ryani\Desktop\Data Analyst COURSE\Data Immersion\E6 - Dashboards and Analytics\UN_DATASET"

# Adjust the path if needed
gdp_df = pd.read_csv(os.path.join(path, '01 Original Data', 'world_gdp_per_capita_2015_2024.csv'))

In [3]:
#all columns
pd.set_option('display.max_columns', None)

In [4]:
gdp_long = (
    gdp_df
      .melt(
          id_vars=['country'],
          var_name='Year',
          value_name='GDP_per_capita'
      )
      .dropna(subset=['GDP_per_capita'])  # remove years with missing GDP
)
# Ensure Year is numeric so it matches df_UN
gdp_long['Year'] = gdp_long['Year'].astype(int)

In [5]:
df_UN = pd.read_csv(os.path.join(path, '03 Prepared Data', 'UN_df_cleaned.csv'))
df_UN.head()

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,VarID,Variant,Time,TPopulation1Jan,TPopulation1July,TPopulationMale1July,TPopulationFemale1July,PopDensity,PopSexRatio,MedianAgePop,NatChange,NatChangeRT,PopChange,PopGrowthRate,DoublingTime,Births,Births1519,CBR,TFR,NRR,MAC,SRB,Deaths,DeathsMale,DeathsFemale,CDR,LEx,LExMale,LExFemale,LE15,LE15Male,LE15Female,LE65,LE65Male,LE65Female,LE80,LE80Male,LE80Female,InfantDeaths,IMR,LBsurvivingAge1,Under5Deaths,Q5,Q0040,Q0040Male,Q0040Female,Q0060,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR
0,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2024,42044.654,42647.492,21532.540,21114.952,65.6827,101.9777,17.1159,1249.770,29.305,1205.676,2.827,24.5188,1492.956,143.175,35.007,4.7606,2.1235,30.443,105.1,243.186,127.754,115.433,5.702,66.2893,64.7043,67.8117,55.6628,54.2730,56.9587,13.3583,12.5950,13.9697,5.6249,5.3444,5.8223,63.496,42.6505,1439.795,80.290,54.4942,114.5120,122.3091,106.3575,249.5329,274.4609,224.8054,101.7436,110.5445,92.7252,198.4914,221.6256,175.9458,-44.089,-1.034
1,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2023,40864.868,41454.761,20924.078,20530.683,63.8457,101.9161,16.9404,1228.733,29.640,1179.786,2.846,24.3551,1469.029,146.316,35.437,4.8403,2.1524,30.366,105.1,240.296,126.080,114.216,5.797,66.0346,64.4667,67.5357,55.5332,54.1516,56.8169,13.3291,12.5710,13.9371,5.6126,5.3354,5.8083,64.348,43.9514,1415.366,81.378,56.1620,117.6520,125.3051,109.6545,253.5386,278.3373,229.1277,103.7876,112.5256,94.8531,201.1085,224.2414,178.7562,-48.958,-1.181
2,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2022,40292.816,40578.842,20475.675,20103.167,62.4967,101.8530,16.7517,1219.461,30.052,572.052,1.410,49.1594,1462.654,148.818,36.045,4.9317,2.1859,30.374,105.2,243.193,128.445,114.748,5.993,65.6170,63.9408,67.2357,55.2361,53.7271,56.6565,13.2796,12.5197,13.8908,5.5964,5.3179,5.7933,65.872,45.1915,1407.952,83.784,58.0385,123.0752,132.7588,112.9641,260.8733,288.3504,233.7682,108.9153,120.5091,97.0285,207.2249,233.3923,181.8401,-647.402,-15.954
3,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2021,39708.008,40000.412,20186.456,19813.956,61.6058,101.8800,16.5753,1133.586,28.340,584.808,1.462,47.4109,1453.685,150.984,36.342,5.0391,2.2114,30.414,105.2,320.099,184.448,135.651,8.002,60.4174,57.0516,64.0793,49.9490,46.5964,53.5737,11.6643,10.7863,12.4028,4.7762,4.5136,4.9680,68.065,46.9239,1397.574,88.175,61.3673,174.0206,216.7301,127.8026,366.1995,434.9700,291.2585,187.4871,243.1744,126.7582,316.9767,388.2573,239.8960,-548.784,-13.719
4,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2020,38429.950,39068.979,19725.450,19343.529,60.1713,101.9744,16.4109,1134.429,29.036,1278.058,3.272,21.1842,1429.983,152.466,36.601,5.1453,2.2580,30.275,105.2,295.554,167.467,128.088,7.565,61.4537,58.4546,64.6563,51.1784,48.2251,54.3079,11.7058,10.6755,12.6095,4.8955,4.4920,5.2120,68.452,48.0086,1373.725,88.718,62.8769,159.3230,190.8581,125.5999,337.1050,395.8878,275.1640,160.4519,201.7709,116.2911,284.3806,344.7921,221.3018,143.634,3.676

In [6]:
gdp_long.head()

                       country  Year  GDP_per_capita
0                  Afghanistan  2015          565.57
1  Africa Eastern and Southern  2015         1479.62
2   Africa Western and Central  2015         1860.73
3                      Albania  2015         3981.73
4                      Algeria  2015         4685.06

In [7]:
gdp_long = gdp_long.rename(columns={'Year': 'Time'})
gdp_long

                          country  Time  GDP_per_capita
0                     Afghanistan  2015          565.57
1     Africa Eastern and Southern  2015         1479.62
2      Africa Western and Central  2015         1860.73
3                         Albania  2015         3981.73
4                         Algeria  2015         4685.06
...                           ...   ...             ...
2645           West Bank and Gaza  2024         2592.31
2646                        World  2024        13673.00
2647                  Yemen, Rep.  2024          433.17
2648                       Zambia  2024         1235.08
2649                     Zimbabwe  2024         2656.41

[2546 rows x 3 columns]

In [8]:
gdp_long = gdp_long.rename(columns={'country': 'Location'})
gdp_long

                         Location  Time  GDP_per_capita
0                     Afghanistan  2015          565.57
1     Africa Eastern and Southern  2015         1479.62
2      Africa Western and Central  2015         1860.73
3                         Albania  2015         3981.73
4                         Algeria  2015         4685.06
...                           ...   ...             ...
2645           West Bank and Gaza  2024         2592.31
2646                        World  2024        13673.00
2647                  Yemen, Rep.  2024          433.17
2648                       Zambia  2024         1235.08
2649                     Zimbabwe  2024         2656.41

[2546 rows x 3 columns]

In [9]:
df_merged = df_UN.merge(
    gdp_long,
    left_on=['Location', 'Time'],
    right_on=['Location', 'Time'],
    how='left'
)


df_merged

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,VarID,Variant,Time,TPopulation1Jan,TPopulation1July,TPopulationMale1July,TPopulationFemale1July,PopDensity,PopSexRatio,MedianAgePop,NatChange,NatChangeRT,PopChange,PopGrowthRate,DoublingTime,Births,Births1519,CBR,TFR,NRR,MAC,SRB,Deaths,DeathsMale,DeathsFemale,CDR,LEx,LExMale,LExFemale,LE15,LE15Male,LE15Female,LE65,LE65Male,LE65Female,LE80,LE80Male,LE80Female,InfantDeaths,IMR,LBsurvivingAge1,Under5Deaths,Q5,Q0040,Q0040Male,Q0040Female,Q0060,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR,GDP_per_capita
0,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2024,42044.654,42647.492,21532.540,21114.952,65.6827,101.9777,17.1159,1249.770,29.305,1205.676,2.827,24.5188,1492.956,143.175,35.007,4.7606,2.1235,30.443,105.1,243.186,127.754,115.433,5.702,66.2893,64.7043,67.8117,55.6628,54.2730,56.9587,13.3583,12.5950,13.9697,5.6249,5.3444,5.8223,63.496,42.6505,1439.795,80.290,54.4942,114.5120,122.3091,106.3575,249.5329,274.4609,224.8054,101.7436,110.5445,92.7252,198.4914,221.6256,175.9458,-44.089,-1.034,NaN
1,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2023,40864.868,41454.761,20924.078,20530.683,63.8457,101.9161,16.9404,1228.733,29.640,1179.786,2.846,24.3551,1469.029,146.316,35.437,4.8403,2.1524,30.366,105.1,240.296,126.080,114.216,5.797,66.0346,64.4667,67.5357,55.5332,54.1516,56.8169,13.3291,12.5710,13.9371,5.6126,5.3354,5.8083,64.348,43.9514,1415.366,81.378,56.1620,117.6520,125.3051,109.6545,253.5386,278.3373,229.1277,103.7876,112.5256,94.8531,201.1085,224.2414,178.7562,-48.958,-1.181,413.76
2,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2022,40292.816,40578.842,20475.675,20103.167,62.4967,101.8530,16.7517,1219.461,30.052,572.052,1.410,49.1594,1462.654,148.818,36.045,4.9317,2.1859,30.374,105.2,243.193,128.445,114.748,5.993,65.6170,63.9408,67.2357,55.2361,53.7271,56.6565,13.2796,12.5197,13.8908,5.5964,5.3179,5.7933,65.872,45.1915,1407.952,83.784,58.0385,123.0752,132.7588,112.9641,260.8733,288.3504,233.7682,108.9153,120.5091,97.0285,207.2249,233.3923,181.8401,-647.402,-15.954,357.26
3,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2021,39708.008,40000.412,20186.456,19813.956,61.6058,101.8800,16.5753,1133.586,28.340,584.808,1.462,47.4109,1453.685,150.984,36.342,5.0391,2.2114,30.414,105.2,320.099,184.448,135.651,8.002,60.4174,57.0516,64.0793,49.9490,46.5964,53.5737,11.6643,10.7863,12.4028,4.7762,4.5136,4.9680,68.065,46.9239,1397.574,88.175,61.3673,174.0206,216.7301,127.8026,366.1995,434.9700,291.2585,187.4871,243.1744,126.7582,316.9767,388.2573,239.8960,-548.784,-13.719,356.50
4,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2020,38429.950,39068.979,19725.450,19343.529,60.1713,101.9744,16.4109,1134.429,29.036,1278.058,3.272,21.1842,1429.983,152.466,36.601,5.1453,2.2580,30.275,105.2,295.554,167.467,128.088,7.565,61.4537,58.4546,64.6563,51.1784,48.2251,54.3079,11.7058,10.6755,12.6095,4.8955,4.4920,5.2120,68.452,48.0086,1373.725,88.718,62.8769,159.3230,190.8581,125.5999,337.1050,395.8878,275.1640,160.4519,201.7709,116.2911,284.3806,344.7921,221.3018,143.634,3.676,510.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2315,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2019,15148.526,15271.368,7243.442,8027.926,39.4762,90.2281,17.1868,348.802,22.840,245.683,1.609,43.0794,475.267,86.554,31.121,3.7480,1.6722,28.054,102.3,126.465,63.441,63.024,8.281,61.0603,58.8296,63.0488,50.0014,47.9008,51.8210,13.0589,11.8528,14.0777,6.2755,5.5311,6.8059,17.470,36.8204,460.431,24.648,52.0763,168.7929,182.4303,156.5231,388.5077,430.3308,353.8247,209.8813,234.9024,190.9142,347.4430,389.2870,313.5975,-103.107,-6.752,1683.91
2316,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2018,14920.378,15034.452,7125.471,7908.981,38.8638,90.0934,17.0221,345.897,23.006,228.148,1.518,45.6619,470.991,84.606,31.327,3.7442,1.6675,28.038,102.3,125.094,62.335,62.759,8.321,60.9055,58.8518,62.7407,49.9180,48.0264,51.5540,13.0484,11.8866,14.0374,6.2709,5.5321,6.8016,17.739,37.6684,456.002,25.211,53.3213,171.1945,183.2572,160.2892,390.8603,427.9629,360.0455,211.7529,232.9385,195.8469,349.1253,385.7373,319.5930,-117.758,-7.833,2271.85
2317,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2017,14704.586,14812.482,7015.107,7797.375,38.2900,89.9675,16.8776,344.031,23.226,215.792,1.457,47.5736,471.228,82.627,31.813,3.7675,1.6709,28.021,102.2,127.197,63.193,64.004,8.587,60.2626,58.3038,62.0161,49.4169,47.6424,50.9489,12.9550,11.8671,13.8842,6.2619,5.5305,6.7886,18.371,38.9036,455.819,26.491,55.5630,178.6085,191.1661,167.3099,403.7493,439.0037,374.3302,220.8267,241.7148,205.0532,360.9658,395.5178,333.0355,-128.241,-8.658,3448.09
2318,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2016,14496.002,14600.294,6909.792,7690.502,37.7415,89.8484,16.7720,348.770,23.888,208.584,1.429,48.5058,477.484,81.397,32.704,3.8282,1.6888,28.001,102.1,128.714,63.650,65.063,8.816,59.7601,57.9399,61.4015,49.0534,47.4448,50.4478,12.9513,11.8694,13.8838,6.2568,5.5300,6.7797,19.266,40.1972,461.437,28.013,57.7766,186.6500,196.9937,177.2655,413.4147,445.2774,386.7537,229.5361,246.6502,216.6720,369.5281,400.3307,344.6680,-140.181,-9.601,1407.42
2319,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2015,14302.024,14399.013,6810.139,7588.874,37.2212,89.7385,16.7289,356.198,24.738,193.978,1.347,51.4586,488.386,80.068,33.918,3.9114,1.7158,27.995,102.1,132.188,65.042,67.146,9.180,58.9895,57.3296,60.4900,48.4595,47.0493,49.6761,12.8452,11.8564,13.6966,6.2508,5.5288,6.7688,20.542,41.8450,471.417,30.096,60.7586,195.9118,206.2659,186.4972,428.6732,456.8205,404.9676,240.6517,255.9804,228.9698,383.5534,410.1757,362.0620,-162.220,-11.266,1386.42

In [10]:
df_USA = df_merged[df_merged['ISO3_code' == 'USA']]
df_USA

KeyError: False

In [22]:
df_merged.isna().sum()

SortOrder            0
LocID                0
Notes             1730
ISO3_code            0
ISO2_code           10
                  ...
Q1560Male            0
Q1560Female          0
NetMigrations        0
CNMR                 0
GDP_per_capita     551
Length: 68, dtype: int64

In [24]:
# Group by country and fill NA values with the mean GDP_per_capita for each country
df_merged['GDP_per_capita'] = df_merged.groupby('Location')['GDP_per_capita'].transform(
    lambda x: x.fillna(x.mean())
)

# If there are countries with all NA values in GDP_per_capita, you might want to handle those separately
# This will fill any remaining NAs with the overall mean
remaining_na_mask = df_merged['GDP_per_capita'].isna()
if remaining_na_mask.any():
    overall_mean = df_merged['GDP_per_capita'].mean()
    df_merged.loc[remaining_na_mask, 'GDP_per_capita'] = overall_mean
    
# Check if there are any remaining NAs
print(f"Remaining NAs in GDP_per_capita: {df_merged['GDP_per_capita'].isna().sum()}")

Remaining NAs in GDP_per_capita: 0

In [25]:
df_merged

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,VarID,Variant,Time,TPopulation1Jan,TPopulation1July,TPopulationMale1July,TPopulationFemale1July,PopDensity,PopSexRatio,MedianAgePop,NatChange,NatChangeRT,PopChange,PopGrowthRate,DoublingTime,Births,Births1519,CBR,TFR,NRR,MAC,SRB,Deaths,DeathsMale,DeathsFemale,CDR,LEx,LExMale,LExFemale,LE15,LE15Male,LE15Female,LE65,LE65Male,LE65Female,LE80,LE80Male,LE80Female,InfantDeaths,IMR,LBsurvivingAge1,Under5Deaths,Q5,Q0040,Q0040Male,Q0040Female,Q0060,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR,GDP_per_capita
0,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2024,42044.654,42647.492,21532.540,21114.952,65.6827,101.9777,17.1159,1249.770,29.305,1205.676,2.827,24.5188,1492.956,143.175,35.007,4.7606,2.1235,30.443,105.1,243.186,127.754,115.433,5.702,66.2893,64.7043,67.8117,55.6628,54.2730,56.9587,13.3583,12.5950,13.9697,5.6249,5.3444,5.8223,63.496,42.6505,1439.795,80.290,54.4942,114.5120,122.3091,106.3575,249.5329,274.4609,224.8054,101.7436,110.5445,92.7252,198.4914,221.6256,175.9458,-44.089,-1.034,471.041111
1,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2023,40864.868,41454.761,20924.078,20530.683,63.8457,101.9161,16.9404,1228.733,29.640,1179.786,2.846,24.3551,1469.029,146.316,35.437,4.8403,2.1524,30.366,105.1,240.296,126.080,114.216,5.797,66.0346,64.4667,67.5357,55.5332,54.1516,56.8169,13.3291,12.5710,13.9371,5.6126,5.3354,5.8083,64.348,43.9514,1415.366,81.378,56.1620,117.6520,125.3051,109.6545,253.5386,278.3373,229.1277,103.7876,112.5256,94.8531,201.1085,224.2414,178.7562,-48.958,-1.181,413.760000
2,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2022,40292.816,40578.842,20475.675,20103.167,62.4967,101.8530,16.7517,1219.461,30.052,572.052,1.410,49.1594,1462.654,148.818,36.045,4.9317,2.1859,30.374,105.2,243.193,128.445,114.748,5.993,65.6170,63.9408,67.2357,55.2361,53.7271,56.6565,13.2796,12.5197,13.8908,5.5964,5.3179,5.7933,65.872,45.1915,1407.952,83.784,58.0385,123.0752,132.7588,112.9641,260.8733,288.3504,233.7682,108.9153,120.5091,97.0285,207.2249,233.3923,181.8401,-647.402,-15.954,357.260000
3,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2021,39708.008,40000.412,20186.456,19813.956,61.6058,101.8800,16.5753,1133.586,28.340,584.808,1.462,47.4109,1453.685,150.984,36.342,5.0391,2.2114,30.414,105.2,320.099,184.448,135.651,8.002,60.4174,57.0516,64.0793,49.9490,46.5964,53.5737,11.6643,10.7863,12.4028,4.7762,4.5136,4.9680,68.065,46.9239,1397.574,88.175,61.3673,174.0206,216.7301,127.8026,366.1995,434.9700,291.2585,187.4871,243.1744,126.7582,316.9767,388.2573,239.8960,-548.784,-13.719,356.500000
4,143,4,NaN,AFG,AF,4,4,Country/Area,5501,Afghanistan,2,Medium,2020,38429.950,39068.979,19725.450,19343.529,60.1713,101.9744,16.4109,1134.429,29.036,1278.058,3.272,21.1842,1429.983,152.466,36.601,5.1453,2.2580,30.275,105.2,295.554,167.467,128.088,7.565,61.4537,58.4546,64.6563,51.1784,48.2251,54.3079,11.7058,10.6755,12.6095,4.8955,4.4920,5.2120,68.452,48.0086,1373.725,88.718,62.8769,159.3230,190.8581,125.5999,337.1050,395.8878,275.1640,160.4519,201.7709,116.2911,284.3806,344.7921,221.3018,143.634,3.676,510.790000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2315,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2019,15148.526,15271.368,7243.442,8027.926,39.4762,90.2281,17.1868,348.802,22.840,245.683,1.609,43.0794,475.267,86.554,31.121,3.7480,1.6722,28.054,102.3,126.465,63.441,63.024,8.281,61.0603,58.8296,63.0488,50.0014,47.9008,51.8210,13.0589,11.8528,14.0777,6.2755,5.5311,6.8059,17.470,36.8204,460.431,24.648,52.0763,168.7929,182.4303,156.5231,388.5077,430.3308,353.8247,209.8813,234.9024,190.9142,347.4430,389.2870,313.5975,-103.107,-6.752,1683.910000
2316,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2018,14920.378,15034.452,7125.471,7908.981,38.8638,90.0934,17.0221,345.897,23.006,228.148,1.518,45.6619,470.991,84.606,31.327,3.7442,1.6675,28.038,102.3,125.094,62.335,62.759,8.321,60.9055,58.8518,62.7407,49.9180,48.0264,51.5540,13.0484,11.8866,14.0374,6.2709,5.5321,6.8016,17.739,37.6684,456.002,25.211,53.3213,171.1945,183.2572,160.2892,390.8603,427.9629,360.0455,211.7529,232.9385,195.8469,349.1253,385.7373,319.5930,-117.758,-7.833,2271.850000
2317,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2017,14704.586,14812.482,7015.107,7797.375,38.2900,89.9675,16.8776,344.031,23.226,215.792,1.457,47.5736,471.228,82.627,31.813,3.7675,1.6709,28.021,102.2,127.197,63.193,64.004,8.587,60.2626,58.3038,62.0161,49.4169,47.6424,50.9489,12.9550,11.8671,13.8842,6.2619,5.5305,6.7886,18.371,38.9036,455.819,26.491,55.5630,178.6085,191.1661,167.3099,403.7493,439.0037,374.3302,220.8267,241.7148,205.0532,360.9658,395.5178,333.0355,-128.241,-8.658,3448.090000
2318,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2016,14496.002,14600.294,6909.792,7690.502,37.7415,89.8484,16.7720,348.770,23.888,208.584,1.429,48.5058,477.484,81.397,32.704,3.8282,1.6888,28.001,102.1,128.714,63.650,65.063,8.816,59.7601,57.9399,61.4015,49.0534,47.4448,50.4478,12.9513,11.8694,13.8838,6.2568,5.5300,6.7797,19.266,40.1972,461.437,28.013,57.7766,186.6500,196.9937,177.2655,413.4147,445.2774,386.7537,229.5361,246.6502,216.6720,369.5281,400.3307,344.6680,-140.181,-9.601,1407.420000
2319,83,716,NaN,ZWE,ZW,716,4,Country/Area,910,Zimbabwe,2,Medium,2015,14302.024,14399.013,6810.139,7588.874,37.2212,89.7385,16.7289,356.198,24.738,193.978,1.347,51.4586,488.386,80.068,33.918,3.9114,1.7158,27.995,102.1,132.188,65.042,67.146,9.180,58.9895,57.3296,60.4900,48.4595,47.0493,49.6761,12.8452,11.8564,13.6966,6.2508,5.5288,6.7688,20.542,41.8450,471.417,30.096,60.7586,195.9118,206.2659,186.4972,428.6732,456.8205,404.9676,240.6517,255.9804,228.9698,383.5534,410.1757,362.0620,-162.220,-11.266,1386.420000

In [26]:
df_merged.to_csv(os.path.join(path, '03 Prepared Data', 'UN_cleaned_GDP.csv'))